Rysboard v4.2: Kicad version
GroupOfRobots/RobotElectronics pull request #1
Opened 2020-05-18 20:59 UTC by mjbogusz

2020-05-19 07:36 UTC, varsheim commented
Schemat:
1. Czy czujniki ToF to są jakieś układy z kondensatorami na pokładzie? Jeśli nie to warto dać po jednym blokującym przy każdym złączu
2. Jeśli są jeszcze dostępne wejścia w RPI4 to warto do nich podłączyć FLAG i BUSY z osobna - jeśli wykorzystujecie te sygnały to może być też potrzebna informacja z którego sterownika konkretny sygnał pochodzi
3. Na D5 i D7 są konkretne napięcia - szkoda energii, może da się obejść bez nich? Do czego one służą?
4. LEDy można wysterować bezpośrednio z PI4 (tylko z większymi rezystorami!). A jeśli przez tranzystor koniecznie to trzeba poprawić orientację tranzystora. Może też warto wykorzystać układ z dwoma tranzystorami jednego typu? Albo dwa oddzielne jednakowe tranzystory? W tej chwili jeden LED jest NO a drugi NZ.
PCB:
1. Trzebaby się odsunąć z miedzią od krawędzi płytki o 0,5mm (albo mniej jeśli maszyna pozwoli)
2. Warto przejrzeć płytkę i pozbyć się takich wcięć w miedzi - jest szansa na wystąpienie dziwnych podtrawień w takich miejscach więc trzeba porobić max. kąty proste ![image](https://user-images.githubusercontent.com/16229877/82296608-bbf6db80-99b1-11ea-98d0-d6971b42e558.png)
3. Jak masa jest na dwóch warstwach to dobrze by było rozrzucić przelotki na całej płytce co parę milimetrów żeby połączenie między nimi było maksymalnie duże
4. Takie rzeczy tylko w ostateczności i tylko usprawiedliwione czymś. Jeśli tylko można to przelotkę trzeba umieścić poza padem, bo teraz układ mechanicznie trzyma się słabo i mogą się pojawić problemy z lutowaniem 
![image](https://user-images.githubusercontent.com/16229877/82298277-2e68bb00-99b4-11ea-8783-a19fc2038ccc.png)

2020-05-19 18:03 UTC, mjbogusz commented
@varsheim 
1. Tak, czujniki są na breakout boardach [tego typu](https://botland.com.pl/pl/cyfrowe-czujniki-odleglosci/11842-vl53l1x-time-of-flight-czujnik-odleglosci-i-swiatla-otoczenia-i2c-pololu-3415.html)
2. Nie bardzo są wejścia, zostało 1 GPIO (niby są GPIO 0 i 1 ale ich używamy do i2c0 przy kamerze i już tu były problemy). W poprzedniej wersji były bez bramek spięte razem ;) natomiast wystarczy nam chyba informacja, że cokolwiek się stało - i tak jak którykolwiek silnik padnie to cały robot się musi zatrzymać, a szczegóły odczytamy po SPI.
3. Masz na myśli D5 i D8? Zabezpieczają przed odwrotnym podpięciem - już mi się jedna przetwornica spaliła... Napięcie wyjściowe z przetwornicy jest odpowiednio dostosowane (5.5V minus 0.5V na diodzie). Bardziej nam zależy na studentoodporności niż długości pracy na baterii (i tak jest kilka godzin).
4. Niedopatrzenie, tam zamiast komplementarnego powinien być 2x NPN. Zmieniam tranzystor na [BC847BS](https://www.tme.eu/pl/details/bc847bs.115/tranzystory-npn-smd/nexperia/). Piny RPi mogą dać max 16mA a w sumie 50mA (na 3.3V), a jeszcze parę rzeczy z tego zasilamy, dlatego tutaj tranzystory. W sumie warto by to przepiąć na 5V razem z paroma innymi rzeczami... jeszcze na to spojrzę.
5. Racja, spróbuję. Robiłem wg [wytycznych PCBWaya](https://www.pcbway.com/capabilities.html), gdzie tego nie wyszczególniają explicite, ale pewnie i tak mają takie ograniczenie.
6. Acid pits, do poprawy jak najbardziej
7. Myślałem nad zrobieniem 5V lub 3V3 fill na drugiej warstwie (dodatkowa pojemność pomiędzy nimi) ale jakoś słabo się rozlewało, trzeba było uważać na inne rzeczy no i przez GND większy prąd płynie (m.in. silniki, które są z baterii bezpośrednio). Przelotki dodam
8. Dobra uwaga, poprzesuwam

2020-05-19 22:51 UTC, kamfor requested changes
Schemat: 
1. Dałbym pull-up-y przy I2C o większej wartości, rzędu 10k, każdy z modułów ToF, czujnik temperatury i IMU mają już standardowo pull-up-y. Jak będzie za dużo to będzie problem z magistralą. 
PCB: 
![obraz](https://user-images.githubusercontent.com/9752118/82384880-200cb480-9a31-11ea-8960-e9b3dafa2534.png)
Tutaj odległość między ścieżkami wynosi koło 0.2 mm, to już na granicy dla napięcia, które jest pomiędzy sąsiadującą ścieżką. Miałem z tym problem w poprzednich wersjach płytki, wystarczało lekkie niedotrawienie i przeskakiwały iskry. Proponuję też wydłużyć pady do tego sterownika i do innych SMD  w sumie też, będzie łatwej to polutować lutownicą.

2020-05-20 14:29 UTC, mjbogusz commented
@kamfor 
1. Nie zauważyłem pull-upów na ToFach. Tylko one są podpięte do tych linii, więc zupełnie tamte pullupy wywalę.
2. Zwiększę odstępy na ile mi rozstaw padów pozwoli, ale przedłużenie w tym momencie może być bardzo trudne, bo mnóstwo ścieżek już mi się obija o inne z obu stron sterowników... Natomiast sterowniki i tak muszą polecieć hotairem (ze względu na ground pad), więc czy to taki problem?

2020-05-23 21:37 UTC, kamfor approved these changes

2020-05-24 14:34 UTC, mjbogusz commented
@kamfor @varsheim 
Zmieniłem zasilanie LEDów i czujników na 5V (ze względu na ograniczenie maksymalnego prądu na 3V3) - przejrzyjcie proszę aktualną wersję, mam nadzieję że to już koniec poprawek ;)

2020-05-26 07:49 UTC, akowalew commented
Generalnie to świetna robota z tą płytką, fajnie się prezentuje!

Jedyne co mi przykuło uwagę to linia SPI_IRQEXT - nie wiem, czy umieszczanie jej na krawędzi płytki jest dobrym wyjściem. Przy lekkim niedotrawieniu, lub po uszczerbku mechanicznym (związanym z montażem, przenoszeniem), mogą być z nią kłopoty.

Z innych rzeczy, to czy czasem RPi nie ma na liniach I2C już wlutowanych pullupów? I, co ważne, czy czasem linie RPi nie są zaprojektowane tylko na 3.3V? Czy podłączenie czujnika pod 5V, i tym samym napędzenie magistrali tym napięciem, nie uszkodzi GPIO?

2020-05-26 15:01 UTC, mjbogusz commented
@akowalew przesunąłem nieco bliżej pinów, teraz jest na równo z krawędzią pola masy. Musiałem też przesunąć `CS1` za złącze RPi, żeby mieć połączenie `GND` do pinu 34, ale oba się zmieściły przy zachowaniu odstępu 0.5mm od krawędzi.

2020-06-23 17:57 UTC, varsheim commented
1. Oznaczyłbym jeszcze + i - na opisie przy gniazdach na baterie - może ułatwić kablowanie.
2. Nie łączyć sąsiadujących padów jedną grubą ścieżką - lepiej połączyć je obok (jak na screenie - można ładniej to zrobić). Wtedy w przypadku braku maski między padami przestrzeń między nimi nie będzie wypełniać się cyną przy lutowaniu.
![image](https://user-images.githubusercontent.com/16229877/85437863-8bdfc100-b58b-11ea-8e85-a7cc5dfab6e4.png)

3. Można jeszcze spróbować poszukać wcięć w miedzi 
![image](https://user-images.githubusercontent.com/16229877/85437890-9437fc00-b58b-11ea-8cfa-039d8015bbed.png)
![image](https://user-images.githubusercontent.com/16229877/85437901-9732ec80-b58b-11ea-8d5d-929a868fb2f6.png)

4. Pewnie masz już wybraną fabrykę - upewnij się, że odległość 0,12mm między ścieżkami jest wystarczająco duża.
![image](https://user-images.githubusercontent.com/16229877/85437922-9bf7a080-b58b-11ea-9b14-de9e0f97493a.png)


5. Coś co może potencjalnie ułatwić pracę z płytką: można dodać testpointy na kluczowych potencjałach. GND jest wystawione na otwory montażowe, ale np. potencjał zasilania silników albo 5V zasilające logikę można już wystawić w wolnym miejscu na przyłożenie sondy miernika.

2020-06-24 19:59 UTC, mjbogusz commented
>     1. Oznaczyłbym jeszcze + i - na opisie przy gniazdach na baterie - może ułatwić kablowanie.
Dodałem, minus celowo pomiędzy ścieżką a pustym polem żeby się nie zlał z jednym bądź drugim
![rysboard_battery_sign](https://user-images.githubusercontent.com/4386503/85621293-57d8ce80-b665-11ea-9a2a-1e096bfced76.png)
>     2. Nie łączyć sąsiadujących padów jedną grubą ścieżką - lepiej połączyć je obok (jak na screenie - można ładniej to zrobić).
Poprawione
![smd_pads_separation](https://user-images.githubusercontent.com/4386503/85621342-6fb05280-b665-11ea-91e0-56422ff2d4da.png)
>     3. Można jeszcze spróbować poszukać wcięć w miedzi
Poprawione, więcej nie znalazłem, ale może już za długo patrzę na tę płytkę ;)
>     4. Pewnie masz już wybraną fabrykę - upewnij się, że odległość 0,12mm między ścieżkami jest wystarczająco duża.
Wstępnie PCBWay, mają do 0.1mm ale zalecają 0.15mm - tyle tutaj jest:
![rysboard_clearance](https://user-images.githubusercontent.com/4386503/85621424-940c2f00-b665-11ea-9536-694bf554c1ca.png)
>     5. Coś co może potencjalnie ułatwić pracę z płytką: można dodać testpointy na kluczowych potencjałach. GND jest wystawione na otwory montażowe, ale np. potencjał zasilania silników albo 5V zasilające logikę można już wystawić w wolnym miejscu na przyłożenie sondy miernika.
5V jest na dwóch pierwszych pinach RPi - między innymi dlatego dodałem numerki przy złączu do tejże. Dodałem keepout na masce na Vdrive (po obu stronach):
![vdrive_testpoint](https://user-images.githubusercontent.com/4386503/85621653-e5b4b980-b665-11ea-8729-19092faee77d.png) ![vdrive_testpoint2](https://user-images.githubusercontent.com/4386503/85621656-e64d5000-b665-11ea-83de-0c2af4c28726.png)

2020-06-27 10:34 UTC, varsheim commented
1. Jeszcze tu znalazłem :)
![image](https://user-images.githubusercontent.com/16229877/85919380-e66a6d00-b86a-11ea-946b-f3395d32e0c3.png)
![image](https://user-images.githubusercontent.com/16229877/85919661-a6f15000-b86d-11ea-8c42-99ebb794a06f.png)

2. Jest miejsce bliżej przetwornika na kondensator - należy go tam przenieść
![image](https://user-images.githubusercontent.com/16229877/85919804-f421f180-b86e-11ea-9f3b-505ab39634a5.png)

Kosmetyka, ale ważna:
3. Dałoby się odbić te duże napisy żeby były zgodnie z kierunkiem opisów elementów? Chyba, że to jest czymś uzasadnione
4. Warto może też dodać opis przy gnieździe SPI z  informacją o kolejności sygnałów MISO MOSI IRQ itd (pewnie trzeba będzie nieco mniejszą czcionką, ale uważam, że zawsze warto taki opis dać, tak jak przy UART jest).
5. Nie wyświetlają mi się modele złączy MOLEX - jeśli to nie błąd u mnie to należałoby je dodać, by również było je widać w projekcie złożenia płyty z elementami mechanicznymi. Wiem, że to jest któraś z kolei płytka i już dawno wzięliście pod uwagę wystające złącza i kable - ale może się w końcu okazać, że ktoś o nich zapomni...

Turbo kosmetyka, ale nadal ważna:
6. I na koniec: płytka będzie robiła dużo większe wrażenie jak się pobawisz jeszcze na warstwie opisu. Można przerobić logo Bionika żeby KiCAD mógł je zaimportować do opisu płytki. Zamiast zwyczajnego napisu KNR BIONIK będzie wtedy narysowane logo koła. Trzeba będzie zrobić na nie troszkę miejsca, ale możesz swoje nazwisko przenieść niżej i już będzie spoko.
![image](https://user-images.githubusercontent.com/16229877/85920225-49abcd80-b872-11ea-941b-83d82279c1ab.png)

7. Na płytce jest dużo przelotek co skutecznie zniszczy wszelkie opisy które będą na nie nachodzić. Nie wiem jak to zrobić w KiCadzie, ale pewnie się da jakoś łatwo: wszelkie MAŁE przelotki, których nie wykorzystasz jako punkty do dotykania sondy miernika można przykryć maską. Czyli na pewno wszystkie przelotki które łączą warstwy GND i wiele innych. Wtedy nawet na nich ładnie przyklei się silkscreen i nie będzie braków w opisach elementów i w ewentualnej grafice. Pomoże to zarówno estetyce jak i w lutowaniu.
Tu zaznaczyłem miejsca gdzie na pewno by wypadło trochę opisu - można temu zapobiec
![image](https://user-images.githubusercontent.com/16229877/85920180-df932880-b871-11ea-8945-73d95fef384f.png)

Poza tym wszystkim: jeśli dobrze ustawiłeś parametry DRC i nie zwraca Ci błędów to płytka jest git

2020-06-27 12:26 UTC, mjbogusz commented
>     1. Jeszcze tu znalazłem :)

Poprawione

>     2. Jest miejsce bliżej przetwornika na kondensator - należy go tam przenieść

Też poprawione

> Kosmetyka, ale ważna:
> 3. Dałoby się odbić te duże napisy żeby były zgodnie z kierunkiem opisów elementów? Chyba, że to jest czymś uzasadnione

Odbite, napis `RysBoard` miał być do krawędzi a pozostałe zgodnie z jego orientacją, ale w sumie to bez różnicy

> 4. Warto może też dodać opis przy gnieździe SPI z informacją o kolejności sygnałów MISO MOSI IRQ itd (pewnie trzeba będzie nieco mniejszą czcionką, ale uważam, że zawsze warto taki opis dać, tak jak przy UART jest).

Dodane

> 5. Nie wyświetlają mi się modele złączy MOLEX - jeśli to nie błąd u mnie to należałoby je dodać, by również było je widać w projekcie złożenia płyty z elementami mechanicznymi. Wiem, że to jest któraś z kolei płytka i już dawno wzięliście pod uwagę wystające złącza i kable - ale może się w końcu okazać, że ktoś o nich zapomni...

Niestety, nie mam modeli tych złącz. Trzeba by je (przynajmniej w uproszczonej bloczkowej wersji) zaprojektować i zaimportować. Zrobiłem na podobnej zasadzie model cewki (L1), bo ma akurat rozmiar, którego nie było w bibliotece KiCADa, ale na ten moment to jest szczyt moich umiejętności modelowania CADowego ;)

Można to dodać jako issue do rozwiązania później.

> Turbo kosmetyka, ale nadal ważna:
> 6. I na koniec: płytka będzie robiła dużo większe wrażenie jak się pobawisz jeszcze na warstwie opisu. Można przerobić logo Bionika żeby KiCAD mógł je zaimportować do opisu płytki. Zamiast zwyczajnego napisu KNR BIONIK będzie wtedy narysowane logo koła. Trzeba będzie zrobić na nie troszkę miejsca, ale możesz swoje nazwisko przenieść niżej i już będzie spoko.

Trochę zabawy z tym było :D ale efekt jest:
![rysboard_logo](https://user-images.githubusercontent.com/4386503/85922161-7b786080-b881-11ea-9fa1-d6aa5ce4ae8c.png)

>     1. Na płytce jest dużo przelotek co skutecznie zniszczy wszelkie opisy które będą na nie nachodzić. Nie wiem jak to zrobić w KiCadzie, ale pewnie się da jakoś łatwo: wszelkie MAŁE przelotki, których nie wykorzystasz jako punkty do dotykania sondy miernika można przykryć maską. Czyli na pewno wszystkie przelotki które łączą warstwy GND i wiele innych. Wtedy nawet na nich ładnie przyklei się silkscreen i nie będzie braków w opisach elementów i w ewentualnej grafice. Pomoże to zarówno estetyce jak i w lutowaniu.
KiCAD domyślnie "maskuje" przelotki (`tented vias`) na etapie eksportu do gerberów:
![rysboard_export_vias](https://user-images.githubusercontent.com/4386503/85922190-a9f63b80-b881-11ea-8c95-bd0ae2ff9616.png)

> Poza tym wszystkim: jeśli dobrze ustawiłeś parametry DRC i nie zwraca Ci błędów to płytka jest git

Ha, "dobre" ustawienie DRC nie jest takie łatwe ;) Ale na obecnych nie pokazuje żadnych błędów.

2020-06-27 15:14 UTC, varsheim commented
MOLEX udostępnia modele elementów na swojej stronie (przynajmniej do tych, których dotychczas używałem). Np. do micro-fitów 2-pinowych na płytce:
https://www.molex.com/molex/products/part-detail/pcb_headers/0430450212
gdzieś tam niżej jest "3D models"

Płytka wygląda super, teraz trzymam kciuki żeby nie trzeba było nic rzeźbić :D

2020-06-27 16:34 UTC, mjbogusz commented
Te modele od Molexa to niełatwa kwestia pod względem licencyjnym... na razie je dodałem (ręcznie każdy przerabiając - trzeba ręcznie ustawić odpowiedni układ odniesienia i pokolorować) i w `LICENSE` dodałem o tym notkę.

Lookin' good!
![rysboard](https://user-images.githubusercontent.com/4386503/85927192-c6f03600-b8a4-11ea-9a88-00701e4d3433.png)

2020-11-12 20:08 UTC, mjbogusz commented
Projekt płytki został przejrzany przez mojego kolegę, naniosłem następujące poprawki:
* D8 (dioda zabezpieczająca przetwornicę przed zasileniem z USB) została przeniesiona do pętli feedbacku; dopasowane rezystory feedbacku
* U5 (podwójny NAND) zmieniłem na taki dostępny na TME
* U4 naprawione połączenie I2C (było na odwrót)
* poprawione połączenie GND do sterowników silników
* poprawione części: dodane PartID (oznaczenie wg producenta) oraz link do TME

2021-03-19 11:45 UTC, mjbogusz commented
Płytka wykonana i polutowana - merge'uję.

2021-03-19 11:46 UTC, merged